services:
  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_DB=trips
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=postgres
    ports:
      - 5433:5432
