[tool.black]
target-version = ['py312']
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.pylint.'MESSAGES CONTROL']
disable = ["C0114", "R0903"]

[tool.pylint.'FORMAT']
max-line-length = 120

[tool.pylint.'DESIGN']
max-attributes = 20
max-bool-expr = 6
max-args = 8

[tool.pylint.'SIMILARITIES']
min-similarity-lines = 5
